[[layouts]]
  type = "file"
  level = "All"
  path = "/var/log/hydra/logs/%date.log"
  layout = "[%datetime.%ms][%l][%session] %content%n"

[[layouts]]
  type = "stdout"
  level = "All"
  layout = "[%datetime.%ms][%l][%session]%content"
